version: 2

project_name: sandbox

builds:
  - main: ./cmd/sandbox
    binary: sandbox
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^readme"
      - "^ci:"

release:
  draft: false

dockers:
  - image_templates:
      - "ghcr.io/davasorus/podman-sandbox-runner:{{ .Version }}-amd64"
      - "ghcr.io/davasorus/podman-sandbox-runner:latest"
    dockerfile: Dockerfile.release
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.source=https://github.com/davasorus/podman-sandbox-runner"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
